### ISSUE TITLE
"Abort trap: 6" error message on 1.8.2 version running on iOS 12.5.1

### ISSUE THREAD

**Issue by cxzero** [nowsecure/fsmon#47]
While running latest version 1.8.2 on `iOS 12.5.1 (iPhone 5s)`, this error appears:
```
iPhone: ~ root# ./fsmon-ios_1.8.2
dyld: Symbol not found: ___chkstk_darwin
  Referenced from: /private/var/root/./fsmon-ios_1.8.2 (which was built for iOS 14.1)
  Expected in: dyld shared cache
 in /private/var/root/./fsmon-ios_1.8.2
Abort trap: 6
```
Reviewing #43, checked that an earlier version 1.6.1 is running fine with the adjustments mentioned there:

```
iPhone: ~ root# ldid -e `which bash` > ent.xml
iPhone: ~ root# ldid -Sent.xml ./fsmon-ios_1.6.1
iPhone: ~ root# ./fsmon-ios_1.6.1 -h           
Usage: ./fsmon-ios_1.6.1 [-Jjc] [-a sec] [-b dir] [-B name] [-p pid] [-P proc] [path]
(...)
```

**Comment by trufae** [comment]
The binaries has been compiled and confirmed to run fine on iOS-14 indeed. I did a tweak in the Makefile, can you confirm this binary works on ios>=10.0 ?

https://github.com/nowsecure/fsmon/releases/download/1.8.2/fsmon-1.8.2-ios.zip

**Comment by cxzero** [comment]
Excelent! I confirm that is working fine:

```
iPhone: ~ root# ./fsmon-1.8.2-ios -h               
Usage: ./fsmon-1.8.2-ios [-Jjc] [-a sec] [-b dir] [-B name] [-p pid] [-P proc] [path]
(...)
```

**Comment by trufae** [comment]
Thanks for confirmation! Ill renove the old 14 deb to avoid confusions
